import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { UserContextProvider } from '@modules/user';
import { userService } from '@modules/user/services';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await userService.fetchCurrentUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <AppRouterCacheProvider>
          <UserContextProvider user={user}>
            {children}
          </UserContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
